. Clone a local copy of the Quick Start templates (including all of its submodules). From the command line, run:
+
----
git clone --recurse-submodules https://github.com/aws-quickstart/quickstart-atlassian-jira.git
----
. Install and set up the https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html[AWS Command Line Interface (CLI)] so that you can create an S3 bucket and upload content to it.
. Create an S3 bucket in your Region:
+
----
aws s3 mb s3://<BUCKET_NAME> --region <AWS_REGION>
----
. Choose which Quick Start template to use:
** quickstart-jira-dc-with-vpc.template.yaml: Use this template for deploying {partner-product-short-name} into a new ASI (end-to-end deployment).
+
** quickstart-jira-dc.template.yaml: Use this template for deploying {partner-product-short-name} into an existing ASI.
. In both templates, the `QSS3BucketName` default value is set to `aws-quickstart`. Replace this value with the name of the bucket you created earlier (`<BUCKET_NAME>`).
. Return to the parent directory of your local clone of the Quick Start templates. From there, upload all the files in your local clone to your S3 bucket:
+
----
aws s3 cp quickstart-atlassian-jira s3://<BUCKET_NAME> --recursive --acl public-read
----
